[settings]
default_model = "cogvideox_2b"
force_gpu = false
use_gpu = true
dtype = "float16"
output_folder = "./outputs"
model_cache_dir = "./models"  # Custom path for model storage
port = 8088
host = "0.0.0.0"
file_retention_time = 3600

[generation]
guidance_scale = 6.0
num_inference_steps = 50

[models]
cogvideox_2b = { name = "THUDM/CogVideoX-2b", type = "cogvideox" }
cogvideox_5b = { name = "THUDM/CogVideoX-5b", type = "cogvideox" }
stable_video = { name = "stabilityai/stable-video-diffusion-img2vid", type = "stablevideo" }
mochi = { name = "genmo/mochi-1-preview", type = "mochi" }